### ISSUE TITLE
what's cv2 and how to install it (i had run 'pip install cv2 --user') ?

### ISSUE THREAD

**Issue by andyyuan78** [jazzsaxmafia/video_to_sequence#3]
envy@ub1404:~/os_pri/github/video_to_sequence$ python download_videos.py 
Traceback (most recent call last):
  File "download_videos.py", line 6, in <module>
    import cv2
ImportError: No module named cv2
## envy@ub1404:~/os_pri/github/video_to_sequence$ pip show cv2

Name: cv2
Version: 1.0
Location: /home/envy/.local/lib/python2.7/site-packages
Requires: 
envy@ub1404:~/os_pri/github/video_to_sequence$ python download_videos.py 
Traceback (most recent call last):
  File "download_videos.py", line 6, in <module>
    import cv2
ImportError: No module named cv2
envy@ub1404:~/os_pri/github/video_to_sequence$

**Comment by jazzsaxmafia** [comment]
It is OpenCV
you can install it by 
pip install opencv

but I recommend installing it from source, as the python binary may not have video processing module in it.
http://opencv.org/

**Comment by andyyuan78** [comment]
after run
suod apt-get install python-opencv
it passed, but new trouble come:

envy@ub1404:~/os_pri/github/video_to_sequence$ python download_videos.py 
Traceback (most recent call last):
  File "download_videos.py", line 3, in <module>
    import pandas as pd
  File "/home/envy/.local/lib/python2.7/site-packages/pandas/**init**.py", line 7, in <module>
    from pandas import hashtable, tslib, lib
  File "pandas/src/numpy.pxd", line 157, in init pandas.hashtable (pandas/hashtable.c:38262)
ValueError: numpy.dtype has the wrong size, try recompiling
envy@ub1404:~/os_pri/github/video_to_sequence$ 

would you like show me the result of 'pip list'?

**Comment by andyyuan78** [comment]
fix by reinstall  pandas

**Comment by mshayeb** [comment]
this works for me: 

pip install opencv-python

**Comment by 700brains** [comment]
failed  on window 

C:\>pip install opencv-python
Collecting opencv
  Could not find a version that satisfies the
 )
No matching distribution found for opencv

**Comment by ghost** [comment]
@mshayeb why does that work?

**Comment by mshayeb** [comment]
check the the version of your python, if you are using python 3 sometimes you have to call pip3 

pip3 install opencv-python 

make sure you are using python3 and not python 2 in run

**Comment by n4nagappan** [comment]
On ubuntu
> sudo apt-get install python-opencv
> pip install opencv-python

**Comment by prabinzz** [comment]
> pip3 install opencv-python

 installs opencv3 what if i want v2 ???

**Comment by ghost** [comment]
`"pip3.6 install opencv"` gives back error message:
`No matching distribution found for opencv`

**Comment by MCSH** [comment]
@prabinzz 
you have to give pip a version, like this:
pip install opencv-python=={version}

**Comment by prashantmore123** [comment]
Install opencv-python instead of cv2.
pip install opencv-python

**Comment by root-sudip** [comment]
for python3.5, You can do by using this command => `sudo pip3 install opencv-python`

**Comment by harshit0511** [comment]
"pip install opencv-python"
works fine on mac os (y)

**Comment by Tianhuanyu** [comment]
ensure you have installed numpy and scipy
then "pip install opencv-python"
or"pip install opencv-python==version"
for u can use source of ustc "pip install opencv-python -i http://pypi.mirrors.ustc.edu.cn/simple"

**Comment by SaiKiranMukka** [comment]
this works for me
"pip3 install opencv-python"

**Comment by jatinmittal199510** [comment]
what @n4nagappan has given, worked for me. Thanks a lot. :)

**Comment by mayank8995** [comment]
Hello every one i am new to python.I am trying to install cv2 package.As everyone is telling to install the open cv instead of cv2, i am getting following error.
Please help me to fix this.
![screenshot from 2018-01-24 08-54-20](https://user-images.githubusercontent.com/15875200/35313012-365f4eac-00e4-11e8-80db-2cea90a74d43.png)

**Comment by mayank8995** [comment]
Hello every one .I am new to python.I have installed open cv but still i get the following error.
![screenshot from 2018-01-24 09-29-54](https://user-images.githubusercontent.com/15875200/35313960-2e3b216a-00e9-11e8-8305-32169d762214.png)

**Comment by biplobb** [comment]
In web2py ,opencv version is 2.But in my local machine opencv version 3.2.ORB_create() is supported in my local machine.But in web2py ORB_create() is not supported . Can you give me any solution?Thanks in advance.

**Comment by Estapraq** [comment]
I have window10 and Python3.6. I did
pip install panda 
pip install opencv-python

worked!

**Comment by gsum** [comment]
for ubuntu 16.04
pip3 install opencv-python //does not work
pip install opencv-python //works for me

**Comment by Matrixsun** [comment]
if you use ananconda , you can install opencv by conda:
conda install opencv

**Comment by black0017** [comment]
If you have multiple versions of python on linux : 

python2    -m pip install opencv-python  # python2.x
python3.5 -m pip install opencv-python  #python3.5
python3.6 -m pip install opencv-python  #python3.6

add  --user  in the end if you have permission issues.

**Comment by eliethesaiyan** [comment]
you might also install `pip install opencv_contrib-python` as some module are missing in opencv

**Comment by zaheerkhancs** [comment]
pip3 install opencv-python

it worked for me.
![screenshot from 2018-07-04 09-30-50](https://user-images.githubusercontent.com/29139858/42279826-054f4c06-7f6d-11e8-8338-b1b5b4cc093e.png)

**Comment by adriendomoison** [comment]
If you've been like me starting to install everything after June 27th 2018, make sure you are not using Python 3.7. Otherwise you'll get the error since this version is not supported yet by OpenCV
```
Collecting opencv-python
  Could not find a version that satisfies the requirement opencv-python (from versions: )
No matching distribution found for opencv-python
```

**Comment by aamirmalik** [comment]
@adriendomoison thanks a lot for this information! I was able to make opencv-python work with python2.7 - just sticking with that for now.

BTW is there a Python3 version you know which supports opencv-python?

**Comment by adriendomoison** [comment]
@aamirmalik OpenCV 3 works with Python 2.7, 3.4, 3.5 and 3.6. 👍

**Comment by kamarajuPrathi** [comment]
@adriendomoison does it work for python 3.7 ?

**Comment by adriendomoison** [comment]
@kamarajuPrathi no, not at the moment sadly

**Comment by ramneek029** [comment]
> If you've been like me starting to install everything after June 27th 2018, make sure you are not using Python 3.7. Otherwise you'll get the error since this version is not supported yet by OpenCV
> 
> ```
> Collecting opencv-python
>   Could not find a version that satisfies the requirement opencv-python (from versions: )
> No matching distribution found for opencv-python
> ```

is there some solution for that ??

**Comment by aaaisha** [comment]
i want install cv2 not cv3 please can anyone tell me the correct command?

**Comment by itsthejoker** [comment]
@aaaisha `pip install opencv-python`, assuming you're in a virtualenv.

**Comment by Mega-Touk** [comment]
running this under raspberry pi wont work because of opencv-python not beeing compiled for ARM on official repo, you first need to follow https://www.piwheels.org then it will be okay to ```pip install opencv-python```

**Comment by belmarca** [comment]
Same error for me using `pip 19.0.1`.

```
$ python --version                                  
Python 3.6.6
$ pip install opencv-python-headless                
Collecting opencv-python-headless
  Could not find a version that satisfies the requirement opencv-python-headless (from versions: )
No matching distribution found for opencv-python-headless
```

**Comment by sahil-motwani** [comment]
> "pip install opencv-python"
> works fine on mac os (y)

cvtColor function is present in opencv-python?
if not than what should I use to get my work done

**Comment by despirit** [comment]
> `"pip3.6 install opencv"` gives back error message:
> `No matching distribution found for opencv`

I use windows 10
on command prompt
python -m pip install opencv-python

**Comment by TomYule** [comment]
`pip3 install opencv-python
pip install opencv-python
`
Collecting opencv-python
  Could not find a version that satisfies the requirement opencv-python (from versions: )
No matching distribution found for opencv-python

I use mac os 10.14.5
python 3.8

I found a lot of information to solve the problem
```
brew tap brewsci/bio
brew tap brewsci/science
brew install opencv
```
Source
https://www.codingforentrepreneurs.com/blog/install-opencv-3-for-python-on-mac/

**Comment by rahul-moorkoth** [comment]
This worked for me.

`pip install opencv-contrib-python`

**Comment by krunal704** [comment]
Not able to install OpenCV 4.1 using pip3 install opencv-python or sudo apt-get install python3-opencv

**Comment by deveshwaripujari** [comment]
> Install opencv-python instead of cv2.
> pip install opencv-python

WHY ???

**Comment by NicolasCombe5555** [comment]
I had a similar problem with macOS Catalina, here is what i did: https://stackoverflow.com/a/61578366/11559619

**Comment by vesko-vujovic** [comment]
I had a problem with opencv, even if i installed everything inside my conda env I couldn't **import cv2** module. I was getting the error "module not found".
What i did i removed pandas with **pip unistall** and **conda remove** after that i installed **pandas** and **open cv** with **_sudo pip3 intstall **_**.

Hope it helps.

**Comment by mkuangdotcom** [comment]
> `pip3 install opencv-python pip install opencv-python ` Collecting opencv-python Could not find a version that satisfies the requirement opencv-python (from versions: ) No matching distribution found for opencv-python
> 
> I use mac os 10.14.5 python 3.8
> 
> I found a lot of information to solve the problem
> 
> ```
> brew tap brewsci/bio
> brew tap brewsci/science
> brew install opencv
> ```
> 
> Source https://www.codingforentrepreneurs.com/blog/install-opencv-3-for-python-on-mac/

MacOS 13.1
Python 3.11.4

Works for me too

**Comment by mkuangdotcom** [comment]
> i want install cv2 not cv3 please can anyone tell me the correct command?

Try this guide:

https://gist.github.com/innat/4af8e9a3accfdcf2511ee4ced26a1d77
